/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Extra process ping (not the locked client ping) */
        get: operations["processHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unauthenticated ping */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agents */
        get: operations["listAgents"];
        put?: never;
        /**
         * Create an agent or a channel
         * @description Default kind=agent. Pass `kind=channel` with `name` and `memberIds`
         *     to create an extra channel (listed on GET /v1/agents). Missing
         *     name, unknown member ids, and channel ids in the list 422.
         *     Omitted memberIds snapshot every current agent.
         */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get one agent */
        get: operations["getAgent"];
        put?: never;
        post?: never;
        /**
         * Delete an agent
         * @description kind=agent including seed `snorlax-bot` returns 204 and is gone
         *     from GET /v1/agents. No auto-reseed; an empty agent roster is OK.
         *     kind=channel including seed `snorlax-bot-group` returns 204 and is
         *     gone from GET /v1/agents. No auto-reseed. User-created agent and
         *     channel DELETE is 204. DELETE of an agent or channel (including
         *     seed) drops that workspace dir.
         */
        delete: operations["deleteAgent"];
        options?: never;
        head?: never;
        /**
         * Patch profile fields
         * @description kind=agent including seed `snorlax-bot`: `{ name, title,
         *     description, avatar }`. Avatar is string|null (data URL or
         *     existing image id). No new upload route. Id is not editable.
         *     User-created kind=channel: `{ name, memberIds, sharedProject }`
         *     returns 200. Seeded channel (`snorlax-bot-group`) identity PATCH
         *     returns 409 `{ error }`. Seed may PATCH `{ sharedProject }` only.
         */
        patch: operations["patchAgent"];
        trace?: never;
    };
    "/v1/agents/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * List transcript messages
         * @description Oldest-first. `before` is a message id cursor for older pages.
         *     For kind=agent (including seed `snorlax-bot`), the list is only
         *     `senderId=user` and that agent. Peer/involve/DM/hop messages are
         *     never in a 1:1. For kind=channel (`snorlax-bot-group`) the default
         *     list is the **timeline**: handoff roots (and other unreplied-to
         *     roots). Thread replies are omitted. Question cards (`kind=widget`)
         *     never appear on the timeline — only in a thread (`?threadId=`).
         *     Pass `threadId` (or `replyTo`)
         *     to load that thread (root + flat replies).
         */
        get: operations["listMessages"];
        put?: never;
        /**
         * Send a user message and stream agent replies
         * @description SSE. Legacy MessageCreate `images: [{ mime, data }]` are stored
         *     and returned at GET /v1/images/{id}; they are never forwarded to
         *     the model. v0.25 `attachmentIds` are included in that turn
         *     (image kinds as image input; file kinds as filename + text
         *     extract when text/*, else a short “user attached {name}” note).
         *     The runtime owns the tool loop (clients never send a tools payload).
         *     A question card ends that agent turn: no more tokens or tools after
         *     `kind=widget` until the user answers or dismisses. Tools still
         *     auto-run; widgets are not approval cards.
         *
         *     For a 1:1 agent, hop 0 is that agent. Mentioned peers and hops
         *     reply in a handoff thread on seed `snorlax-bot-group` when present
         *     (ignore body `channelId`). Else if the 1:1 POST body has `channelId`
         *     and it is an existing kind=channel row, log there. Else skip the
         *     log (no handoff, no jump chip; still run B and A's report-back).
         *     Unknown/stale `channelId` after seed delete: skip log, do not 422,
         *     do not recreate seed. Not in either 1:1. A still
         *     answers in the 1:1. When the peer posts a material reply (or is
         *     hop/cap dropped), A is woken with a report-back pack and posts
         *     another assistant turn in that 1:1 (not a hop). Multiple
         *     `message.done` events on the same stream; the POST stays open
         *     until every mentioned peer has finished or been dropped and A
         *     has reported for each. Optional `replyTo` on the body posts into
         *     an existing channel thread. @mention inside an extra channel
         *     stays in that channel's thread.
         *
         *     422 only for an unknown mention chip id (and `@everyone` chip
         *     outside the group). Typed `@foo` with no chip is plain text.
         *     Agent-authored unknown `@Name` is ignored. `@everyone` is group-only.
         *
         *     - event `message.delta` data `{ id, role: "assistant", delta, senderId, senderName, senderAvatar }`
         *     - event `message.done` data full Message (not wrapped)
         *     - event `tool.start` data ToolTrace `{ id, name, summary, senderId, senderName }`
         *     - event `tool.done` data ToolTrace `{ id, name, summary, ok, senderId, senderName }`
         *     - event `error` data `{ error }` (string)
         *
         *     Multiple `message.done` events may appear on one stream when more
         *     than one agent speaks in this transcript, and after each persisted
         *     tool line (`kind=tool`) or question card (`kind=widget`). Tool activity is stored as Message
         *     `kind=tool` with short content (`Read src/a.ts`, `Ran ls`,
         *     `Fetched …`), same senderId as the speaking agent, in that
         *     transcript only (1:1 if A tools; channel thread if B tools).
         *     Report-back into A's 1:1 is a normal assistant `kind=message` as A
         *     and does not copy B's tool lines or B's widgets. A turn that ran tools always
         *     finishes with a normal assistant `kind=message` (streamed and
         *     persisted) unless the model asked a question card —         then the POST
         *     SSE ends on that `kind=widget` `message.done` (no `widget.*` event).
         *     A Connect card for an unauthenticated MCP plugin is the same
         *     persist-then-`message.done` shape with `kind=connect` (no
         *     `connect.*` event on emit). Answer with `{ widgetReply: { id, values?, dismissed? } }` on that
         *     transcript; that is not a user Message. Connect is
         *     `{ connectReply: { id } }` or `{ dismissed: true }` — also not a
         *     user Message. Dismiss does not wake the
         *     agent and does not return a URL. `{ id }` while the plugin still
         *     needs auth stays pending, emits `event: connect.url` data
         *     `{ url, pluginId }`, then ends this POST; the client opens the OS
         *     browser. When OAuth completes (runtime GET callback or POST
         *     `{ code, state }`), the same Message is PATCHed to
         *     connectStatus=connected and the agent turn continues (tools
         *     auto-run). If the plugin is already connected, `{ id }` PATCHes
         *     connected and continues this POST as hop-0. A pick continues this
         *     POST as hop-0 with the values. A
         *     normal content send while a card is pending is 409 unless
         *     dismissOnMoveOn (then auto-dismiss, no wake for the widget, then
         *     the new user message). Connect pending has no dismiss-on-move-on:
         *     content is 409 until connect or dismiss. One pending widget per transcript (409 if
         *     the model emits a second). One pending connect card per transcript.
         *     Unknown id or already closed is 422.
         *     Empty model text or an inference error after tools still
         *     produce that follow-up; do not end on only a `kind=tool` line or
         *     `event:error` with no saved assistant message. Live `tool.start` /
         *     `tool.done` traces stay additive. Clients that do not understand
         *     `tool.*` skip those events and may still render `kind=tool` rows from GET.
         *     MCP tools reuse the same traces (`Used server__tool` / `Ran …`).
         *     Unknown events must still be ignorable. Widget rows follow
         *     senderId of the speaking agent (LEFT). GET 1:1 is still only user
         *     + that agent.
         */
        post: operations["postMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/routines": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * List routines assigned to this agent
         * @description JSON array of Routine (not wrapped). A routine is cron XOR
         *     trigger. `kind` is `cron` | `webhook` | `slack` | `github`.
         *     Cron rows have `schedule` (5-field, Asia/Taipei) and optional
         *     `scheduleLabel` (`Weekdays 9:00`). Webhook rows have
         *     `webhookUrl` (full URL with secret token in the path; Copy on
         *     the identity pane; clients must not paint it). Slack/GitHub
         *     rows are omitted unless GET /v1/plugins shows that plugin
         *     status=connected; when present they may have `label`
         *     (e.g. `Slack #eng`). Null fields are
         *     omitted (`webhookUrl` is absent on cron rows). Missing agent
         *     is 404. kind=channel is 409 (routines are agent-only). Used by
         *     the agent info pane (list + enable/pause + Copy for webhook
         *     URL). v0.17: trailing 12px `Add` opens a 320px Add routine
         *     sheet (name + 44px SKILL.md rows + segmented Schedule/Webhook;
         *     v0.23 adds Slack/GitHub segments only when that plugin is
         *     connected). Every row has muted 12px `Remove` (`Remove {name}?`).
         *     Pause stays. No edit-in-place. Humanized trigger
         *     line (`Webhook` / `Weekdays 9:00` / `Slack #eng` /
         *     `GitHub owner/name`) is a client concern. Webhook
         *     rows show 12px muted Copy left of Remove, then the pause switch
         *     (`Copied` for 1.5s); do not paint webhookUrl. Slack/GitHub rows
         *     have no Copy. Do not emit Connect cards from
         *     the pane.
         */
        get: operations["listRoutines"];
        put?: never;
        /**
         * Create a routine for this agent
         * @description Body is cron XOR trigger. Cron:
         *     `{ name, skill, schedule }` (5-field or named hour, Asia/Taipei).
         *     Webhook: `{ name, skill, trigger: { type: webhook } }` — 201
         *     with `webhookUrl` (token in the path). POST of an event routine
         *     without a trigger is 422. POST with both schedule and trigger is
         *     422. Slack: `{ name, skill, trigger: { type: slack, channel } }`
         *     → 201 `kind=slack` `label="Slack {channel}"` (no webhookUrl).
         *     GitHub: `{ type: github, repo }` (`owner/name`, no wildcards) →
         *     201 `kind=github` `label="GitHub {repo}"`. Unconnected plugin,
         *     empty channel/repo, or wildcards → 422. Webhook works with zero
         *     plugins. 422 missing name/skill, unknown skill, bad cron, or
         *     channel id. Missing agent is 404. Pause stays PATCH `{ enabled }`.
         *     DELETE is a separate operation.
         */
        post: operations["createRoutine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/routines/{routineId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                routineId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a routine
         * @description `DELETE /v1/agents/{id}/routines/{routineId}` → 204, gone from
         *     GET. Unknown routine is 404. kind=channel is 409. Missing agent
         *     is 404. Pause stays a PATCH; this is Remove, not pause.
         */
        delete: operations["deleteRoutine"];
        options?: never;
        head?: never;
        /**
         * Enable or pause a routine
         * @description `{ enabled: false }` pauses. `{ enabled: true }` resumes. This
         *     thin. No name/skill/schedule patch this slice.
         *     Unknown routine is 404. kind=channel is 409.
         */
        patch: operations["patchRoutine"];
        trace?: never;
    };
    "/v1/hooks/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Secret token minted into webhookUrl. Not the routine id. */
                token: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fire a webhook routine
         * @description POST the minted webhookUrl. Does not use SNORLAX_TOKEN. The
         *     secret is the path token, not a query string and not a header.
         *     Unknown token, a non-webhook routine, or a paused webhook is
         *     404 and does not run. Success is 204, then the runtime runs
         *     that agent's SKILL.md into that agent's 1:1 as LEFT kind=message
         *     senderId=A with routineName. No catch-up. Isolation stands:
         *     never paint B in A's 1:1.
         */
        post: operations["fireWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/skills": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * List discovered skills for this agent
         * @description Thin discovery. Runtime reads SKILL.md from
         *     SNORLAX_DATA_DIR/skills/<slug>/SKILL.md (and may also see a
         *     workspace SKILL.md). Returns `{ id, name }` per file (`id` is
         *     the directory slug or frontmatter name). Empty list is 200
         *     `[]`. Not a marketplace catalog. kind=channel is 409. Clients
         *     never read the host disk. v0.17 Add-routine picker reuses this
         *     list (`id` is the POST skill). v0.18 GET/PATCH/DELETE of one
         *     skill is `/skills/{sid}`; this list stays `{ id, name }` (no
         *     body). v0.22 blank New is POST `{ name, body }` (same list
         *     shape); body omitted still teach-a-task.
         */
        get: operations["listSkills"];
        put?: never;
        /**
         * Create a skill (blank New or recorded demonstration)
         * @description One route, two bodies. Discriminate on `body` omitted vs present.
         *     Do not treat omitted body as blank create. No second POST path.
         *
         *     `{ name, body }` (body present, non-empty) is blank New skill.
         *     Writes SNORLAX_DATA_DIR/skills/<slug>/SKILL.md via
         *     slugify_skill_name. **201** Skill `{ id, name }` (listed shape,
         *     not SkillBody). No computer capture required. `body` is the
         *     same shape as PATCH: full SKILL.md source (frontmatter plus
         *     recipe) or recipe-only. Empty name or empty body → **422**.
         *
         *     `{ name }` with body omitted is still record-to-skill. Writes
         *     SKILL.md from the capture stopped with DELETE `/computer/record`
         *     (same v0.9 load path). 201 Skill `{ id, name }`. Discard is skip
         *     this POST — no SKILL.md. Empty name or no pending capture
         *     (still recording, never recorded, or discarded by next record /
         *     session end) is 422 (`no pending capture` / name).
         *
         *     kind=channel is 409. Missing agent is 404. Edit is GET/PATCH
         *     `/skills/{sid}`. No marketplace.
         */
        post: operations["createSkill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/skills/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                /**
                 * @description Skill id (directory slug under skills/<sid>/SKILL.md, or
                 *     frontmatter name). Unknown is 404.
                 */
                sid: string;
            };
            cookie?: never;
        };
        /**
         * Get a skill's SKILL.md source
         * @description `{ id, name, body }`. `body` is the full SKILL.md **source**
         *     (YAML frontmatter plus recipe), not a rendered preview.
         *     kind=channel is 409. Missing agent is 404. Unknown sid is 404.
         *     List stays GET `/skills` `{ id, name }` (no `body` field).
         */
        get: operations["getSkill"];
        put?: never;
        post?: never;
        /**
         * Remove a skill
         * @description `DELETE /v1/agents/{id}/skills/{sid}` → **204**, gone from GET.
         *     Unknown sid is 404. kind=channel is 409. Missing agent is 404.
         *     Confirm chrome is `Remove {name}?`. Does not cascade-delete
         *     routines that still name the skill; those stay until a later
         *     422 on use.
         */
        delete: operations["deleteSkill"];
        options?: never;
        head?: never;
        /**
         * Edit a skill name and SKILL.md source
         * @description `{ name, body }` → **200** `{ id, name, body }`. Writes that
         *     SKILL.md in place. Keep the slug / skill `id` unless a name
         *     change truly requires a new slug — prefer keep `id` stable.
         *     Empty name or body is **422**. kind=channel is 409. Missing
         *     agent is 404. Unknown sid is 404. Blank New is POST `/skills
         *     { name, body }` (body present). `{ name }` omitted body stays
         *     teach-a-task.
         */
        patch: operations["patchSkill"];
        trace?: never;
    };
    "/v1/agents/{id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * List the conversation workspace
         * @description Runtime read of the existing sandbox (same roots as workspace_for).
         *     Clients never call tools or the model. Path default `.`. Empty
         *     workspace is `{ entries: [] }` and does not create the dir.
         *     `root` is sandbox-relative (`workspaces/agents/{id}` or
         *     `workspaces/channels/{id}`), never a Mac folder path.
         *     1:1 → that agent's workspace. Channel + sharedProject true →
         *     channel sandbox. Channel + sharedProject false → first member
         *     agent's workspace. Isolation: a 1:1 listing never includes
         *     another 1:1's files or a channel sandbox.
         */
        get: operations["listWorkspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/workspace/file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Read a text file from the conversation workspace
         * @description UTF-8 text only. Size cap matches read_file (256k); larger text
         *     sets `truncated: true`. Binary (NUL in the first 4k) is 422
         *     `{ error: "binary / too large" }` — not a hex dump. Path escape
         *     is 422. Missing file is 404. Path default `.`.
         */
        get: operations["getWorkspaceFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/computer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Per-agent computer preview
         * @description Runtime-owned 1280x800 sandbox display. kind=channel is 409.
         *     Unknown agent is 404. `{ hasSandbox, width: 1280, height: 800,
         *     imageUrl }`. `imageUrl` is present only when hasSandbox is true:
         *     GET `/v1/agents/{id}/computer/screenshot` (Bearer, image/png).
         *     No sandbox: hasSandbox false, omit imageUrl, no frame on clients
         *     (`No computer yet.`). Idle desktop still returns a 1280x800 shot
         *     (always on). When hasSandbox, GET may include `driving`: `user`
         *     (takeover session), `agent` (agent last drove the sandbox), or
         *     `idle`. Omitted when hasSandbox is false. When hasSandbox, GET
         *     may include `recording` (boolean): true after POST
         *     `/computer/record`, false otherwise (idle, session without
         *     Record, or after DELETE `/computer/record`). Omitted when
         *     hasSandbox is false. Takeover is POST
         *     `/v1/agents/{id}/computer/session` (201 `{ sessionId }`) then
         *     pointer/key while the session exists. Workspace file-tree GETs
         *     are unchanged.
         */
        get: operations["getComputer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/computer/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Bearer PNG screenshot of the agent sandbox display
         * @description image/png of the live 1280x800 framebuffer. Same SNORLAX_TOKEN
         *     as other GETs. kind=channel is 409. Unknown agent is 404. No
         *     sandbox is 404. Idle still returns a desktop shot. Not a
         *     decorative static asset. Takeover input is POST session then
         *     pointer/key, not this GET.
         */
        get: operations["getComputerScreenshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/computer/session": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a desktop takeover session
         * @description 201 `{ sessionId }`. User is driving; agent is paused and must
         *     not run tools that drive the sandbox (409). kind=channel is 409.
         *     Unknown agent is 404. No sandbox is 404. Idempotent if a session
         *     is already open (same sessionId). Desktop only this slice; iOS
         *     does not POST this route.
         */
        post: operations["openComputerSession"];
        /**
         * End the takeover session (Done)
         * @description 204. Returns to display-only; the next screenshot is the last
         *     frame. kind=channel is 409. Unknown agent is 404. Idempotent
         *     if no session is open. `DELETE .../computer/session/{sessionId}`
         *     also 204 for that session; unknown sessionId is 404.
         */
        delete: operations["closeComputerSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/computer/session/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                sessionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * End a takeover session by id (Done)
         * @description 204. Same as DELETE `/computer/session` for this sessionId.
         *     Unknown sessionId is 404. kind=channel is 409. Unknown agent
         *     is 404.
         */
        delete: operations["closeComputerSessionById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/computer/pointer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pointer event in sandbox coordinates
         * @description Body `{ x, y, type }` with x/y in 1280x800. `type` is `move`,
         *     `down`, `up`, or `click`. 200. Requires an open session (409
         *     without one). kind=channel is 409. Unknown agent is 404. No
         *     sandbox is 404.
         */
        post: operations["postComputerPointer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/computer/key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Key event in the sandbox
         * @description Body `{ key, type, text? }`. `type` is `down`, `up`, or `type`.
         *     When `type` is `type`, `text` is preferred if present else `key`.
         *     200. Requires an open session (409 without one). kind=channel is
         *     409. Unknown agent is 404. No sandbox is 404.
         */
        post: operations["postComputerKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/computer/record": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start capture inside a takeover session
         * @description Record only inside a takeover session. 201 `{ recording: true }`.
         *     409 without session (`no computer session`) / already recording
         *     (`already recording`). kind=channel is 409. Missing agent is
         *     404. Desktop only this slice; iOS does not POST this route.
         *     Capture records pointer/key (and screenshot context) until
         *     DELETE this path. A new POST while a stopped capture is pending
         *     discards that pending capture.
         */
        post: operations["startComputerRecord"];
        /**
         * Stop capture (no SKILL.md yet)
         * @description 204. Does NOT write SKILL.md. Capture stays pending until POST
         *     `/v1/agents/{id}/skills` (save) or discard (skip that POST;
         *     next record or session end discards). kind=channel is 409.
         *     Missing agent is 404. No session is 409. Idempotent if not
         *     recording while a session exists.
         */
        delete: operations["stopComputerRecord"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List runtime-owned MCP plugins
         * @description JSON array of Plugin (not wrapped): `{ id, name, status }` where
         *     status is `connected` or `needsAuth`. Catalog may be empty.
         *     Runtime-global (not per-agent). Clients never speak MCP; this is
         *     Settings chrome only, not the agent pane. Hand-edited mcp.json
         *     under SNORLAX_DATA_DIR still loads stdio and LAN servers. Add
         *     custom is POST this path. DELETE /v1/plugins/{id} uninstalls
         *     (disconnect + drop from catalog). No separate disconnect
         *     endpoint. No store / search / public marketplace. Curated
         *     Slack/GitHub list is GET /v1/plugins/catalog.
         */
        get: operations["listPlugins"];
        put?: never;
        /**
         * Add a custom MCP plugin
         * @description Body `{ name, transport: "stdio" | "url", command?, args?: string[],
         *     url? }`. Returns 201 `{ id, name, status: connected|needsAuth }`.
         *     stdio: command required (args optional). 422 if name or command
         *     missing. url: url required; allow https and http (LAN). 422 if
         *     missing/invalid. Persists into mcp.json under SNORLAX_DATA_DIR.
         *     Does not auto-open a kind=connect card. Clients never speak MCP.
         *     Catalog Add is this same POST (no extra sheet / no POST
         *     /catalog). No store / search / public marketplace.
         */
        post: operations["createPlugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plugins/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List curated MCP plugins
         * @description JSON array of PluginCatalogEntry (not wrapped):
         *     `{ id, name, transport, command?, args?, url? }`. Same transport
         *     fields as PluginCreate so clients POST /v1/plugins with that
         *     body as-is (name + transport + command/args or url). Omit nulls.
         *     Curated in runtime code — not mcp.json, not a remote registry,
         *     no search. Exactly two entries when neither is installed, in
         *     this order: Slack (`id: slack`, `name: Slack`) then GitHub
         *     (`id: github`, `name: GitHub`). Each bakes a real stdio or url
         *     transport that POST /v1/plugins already accepts (npx stdio is
         *     fine). Omit a row when GET /v1/plugins already has a connected
         *     or needsAuth plugin whose id or name matches that kind (same
         *     needle as plugin_kind_connected: `slack` / `github` in id+name).
         *     If both are installed → 200 `[]`. Empty catalog is 200 `[]`
         *     (clients hide the Catalog header). Do not 404. No POST /catalog.
         *     No uninstall-from-catalog. Bearer as other /v1 routes.
         *     Runtime-global. Not a public store.
         */
        get: operations["listPluginCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plugins/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Uninstall a plugin
         * @description Disconnects the live session and drops the plugin row and
         *     credentials from the runtime MCP catalog. 204. Unknown id is 404.
         *     Does not auto-open a connect card. No separate disconnect
         *     endpoint. Clients never speak MCP.
         */
        delete: operations["deletePlugin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plugins/{id}/auth": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start plugin browser auth
         * @description Returns `{ authorizationUrl }` for the OS browser (desktop system
         *     browser; iOS ASWebAuthenticationSession). The OAuth callback hits
         *     the runtime. Unknown id is 404. After the browser finishes,
         *     GET /v1/plugins shows `connected` and tools auto-run (no approval
         *     widgets). A pending kind=connect card for this plugin is PATCHed
         *     to connected and that agent turn continues. Connect-card Connect
         *     tap is POST connectReply, which emits `connect.url` when the
         *     plugin still needs auth.
         */
        post: operations["startPluginAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a chat attachment
         * @description Bearer. Multipart field `file`. `{id}` is the same conversation
         *     as POST /v1/agents/{id}/messages (kind=agent 1:1 or kind=channel).
         *     Missing conversation 404. No /v1/chats/ resource. 201
         *     `{ id, kind, name, url, size }`. kind is `image` for image/*
         *     (not video), else `file`. url is GET /v1/attachments/{id} on
         *     this host (Bearer). Over 10MB → 422 `Max 10MB.`. video/* → 422
         *     `Video isn’t supported yet.`. Empty file 422. User-right only
         *     this slice — bind via MessageCreate.attachmentIds on the next
         *     send. Agent-sent attachments wait.
         */
        post: operations["postAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attachments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch attachment bytes
         * @description Bearer. Supports Attachment.url / Message.attachments[].url.
         *     Content-Type is the stored mime. 404 unknown. No unauthenticated
         *     fetch. Not /v1/chats/.
         */
        get: operations["getAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch persisted image bytes
         * @description Supports Message.images[].url. Never sent to the model.
         */
        get: operations["getImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            ok: true;
            /** @constant */
            name: "Snorlax-Bot";
            version: string;
        };
        Agent: {
            /**
             * @description Seed 1:1 is `snorlax-bot`. Seeded channel is `snorlax-bot-group`.
             *     Never reuse `snorlax-bot` as the channel transcript.
             */
            id: string;
            /** @description Display name. Seed 1:1 is Snorlax. Seeded channel is Snorlax-Bot. */
            name: string;
            title: string;
            description: string;
            /**
             * @description Data URL, existing image id, or null. Empty/null shows initials
             *     from name.
             */
            avatar: string | null;
            /**
             * @description Clients show a muted "Channel" subtitle from kind=channel.
             *     Do not guess from id. Seed agent is kind=agent.
             * @enum {string}
             */
            kind: "agent" | "channel";
            /** @description Agent ids in a channel. Empty for kind=agent. Channel members come from memberIds. */
            memberIds: string[];
            /**
             * @description Channel shared-project toggle, default false. When true, channel
             *     / handoff turns use workspaces/channels/{id}/. When false, the
             *     speaking agent's workspace. Ignored (always false) on kind=agent.
             *     Not a picker for a folder on the host Mac.
             */
            sharedProject: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AgentCreate: {
            /** @default New agent */
            name: string;
            /** @default  */
            title: string;
            /** @default  */
            description: string;
            avatar?: string | null;
            /**
             * @description `channel` creates an extra channel listed on GET /v1/agents.
             * @default agent
             * @enum {string}
             */
            kind: "agent" | "channel";
            /**
             * @description Channel members when kind=channel. Empty/omitted snapshots
             *     every current agent. Unknown ids and channel ids 422.
             *     Ignored for kind=agent.
             */
            memberIds?: string[];
        };
        AgentPatch: {
            name?: string;
            title?: string;
            description?: string;
            /**
             * @description Data URL, existing image id, or null. Empty/null shows initials
             *     from name. PATCH only; no new upload route.
             */
            avatar?: string | null;
            /**
             * @description User-created channel members. Agent ids only. Seed channel
             *     identity PATCH is 409. Unknown ids and channel ids 422.
             */
            memberIds?: string[];
            /**
             * @description Channel shared-project toggle. Seed channel may PATCH this
             *     field only. kind=agent returns 422.
             */
            sharedProject?: boolean;
        };
        ImageOut: {
            id: string;
            mime: string;
            url: string;
        };
        ImageIn: {
            mime: string;
            /** @description Base64 image bytes. Persisted; never sent to the model. */
            data: string;
        };
        Attachment: {
            id: string;
            /**
             * @description image for image/* (not video); else file.
             * @enum {string}
             */
            kind: "image" | "file";
            name: string;
            /** @description Bearer GET /v1/attachments/{id} on this host. */
            url: string;
            /** @description Byte length. */
            size: number;
        };
        Mention: {
            /** @description Agent id, or `everyone` for @everyone. */
            id: string;
            name: string;
        };
        HandoffRef: {
            channelId: string;
            threadId: string;
        };
        Message: {
            id: string;
            /**
             * @description Transcript owner. `snorlax-bot` is the Snorlax 1:1. `snorlax-bot-group`
             *     is the seeded channel. 1:1 lists are only user + that agent.
             */
            agentId: string;
            /** @enum {string} */
            role: "user" | "assistant";
            /**
             * @description Plain string. Runtime stores user and model text as-is.
             *     Do not add contentType, mime, html, or blocks[]. Do not rewrite
             *     assistant text to HTML or split one Message into many. SSE
             *     message.delta is text chunks of this same string. User
             *     messages stay plain text as stored. v0.11 clients render
             *     assistant LEFT kind=message as markdown. widget, connect,
             *     tool, and routineName stay. No MCP mix-in.
             */
            content: string;
            images: components["schemas"]["ImageOut"][];
            /**
             * @description User-right only this slice. Assistant rows are []. v0.25
             *     uploads bound via attachmentIds. Not a list-endpoint wrapper.
             */
            attachments: components["schemas"]["Attachment"][];
            /** Format: date-time */
            createdAt: string;
            /** @description `user` or an agent id. Layout uses senderId === user → right; else left. */
            senderId: string;
            senderName: string;
            senderAvatar: string | null;
            /** @description User→current agent is 0. Mentions increment. Max depth 3. */
            hop: number;
            mentions: components["schemas"]["Mention"][];
            /**
             * @description Channel handoff root is `handoff` (LEFT card authored as A).
             *     Tool activity is `tool` (LEFT 12px muted status, short content
             *     like `Read src/a.ts` / `Ran ls` / `Fetched …`, same senderId as
             *     the agent). Question card is `widget` (LEFT card under the
             *     speaking agent's 20px avatar + 13px name; not a user-right
             *     bubble and not a token stream). Connect card is `connect`
             *     (same LEFT chrome family as widgets, NOT kind=widget). Default
             *     `message`. Do not drop kind=message|handoff|tool.
             * @enum {string}
             */
            kind?: "message" | "handoff" | "tool" | "widget" | "connect";
            /** @description Channel thread id. Null on timeline roots and on 1:1s. */
            replyTo?: string | null;
            /**
             * @description Set on the originating **user** message when the user caused a
             *     handoff (an @chip in a 1:1). Absent/null if hop/cap dropped
             *     the mention, or if an agent DM created the thread without a
             *     user @chip. Not a fake speaker.
             */
            handoff?: components["schemas"]["HandoffRef"];
            /** @description Handoff root. The ask B should answer. */
            userAsk?: string | null;
            /**
             * @description Handoff root. Last 8 user+A messages of the originating 1:1,
             *     cap 2k characters, oldest dropped.
             */
            brief?: string | null;
            /** @description Count of thread replies under a timeline root. */
            replyCount?: number;
            /**
             * @description Set on kind=widget. Card fields only. Status and picked values
             *     are widgetStatus / widgetValues on this Message so GET can
             *     re-render the same card. Absent on other kinds. Never a
             *     user-right bubble.
             */
            widget?: components["schemas"]["Widget"];
            /**
             * @description Set on kind=connect. Card fields only. Status lives on
             *     connectStatus on this Message so GET can re-render the same
             *     card. Absent on other kinds. Never a user-right bubble.
             */
            connect?: components["schemas"]["ConnectCard"];
            /**
             * @description Set on kind=connect. pending until auth finishes or dismiss;
             *     connected after the OAuth callback PATCHes this row; dismissed
             *     after `{ dismissed: true }`.
             * @enum {string}
             */
            connectStatus?: "pending" | "connected" | "dismissed";
            /**
             * @description Set on kind=widget. pending until a widgetReply; resolved after
             *     a pick; dismissed after decline or dismissOnMoveOn.
             * @enum {string}
             */
            widgetStatus?: "pending" | "resolved" | "dismissed";
            /**
             * @description Chosen option values (or custom text) after a pick. Empty while
             *     pending or dismissed.
             */
            widgetValues?: string[];
            /**
             * @description Set when this assistant Message is a routine result
             *     (cron or webhook). 12px kicker under the sender name.
             *     12px muted kicker under the sender name. Absent on ordinary
             *     turns. Not a channel post.
             */
            routineName?: string | null;
        };
        WidgetOption: {
            label: string;
            /** @description Picked value. Defaults to label. */
            value?: string;
            description?: string;
            /**
             * @default default
             * @enum {string}
             */
            style: "default" | "primary" | "danger";
        };
        Widget: {
            /** @description Natural-language question. Not a menu instruction. */
            prompt: string;
            helpText?: string | null;
            options: components["schemas"]["WidgetOption"][];
            /** @default false */
            allowCustom: boolean;
            /** @default false */
            multiSelect: boolean;
            /**
             * @description If true, a normal content send auto-dismisses this card (no
             *     agent wake for the widget) and proceeds. If false, that send
             *     is 409 while the card is pending.
             * @default false
             */
            dismissOnMoveOn: boolean;
        };
        WidgetReply: {
            /** @description Message id of the pending kind=widget row. */
            id: string;
            /**
             * @description Option values (default label) or custom text if allowCustom.
             *     multiSelect is several values; otherwise more than one is 422.
             *     Not persisted as a user Message.
             */
            values?: string[];
            /**
             * @description Decline the pending card. Updates that same Message to
             *     widgetStatus=dismissed. Does not create a user Message and
             *     does not wake the agent.
             * @default false
             */
            dismissed: boolean;
        };
        ConnectCard: {
            /**
             * @description Natural prompt on the card, e.g. `Connect Slack to read your
             *     channels.`
             */
            prompt: string;
            /** @description Plugin id from GET /v1/plugins. */
            pluginId: string;
            /** @description Optional 12px muted help, e.g. `Opens your browser to sign in.` */
            helpText?: string | null;
        };
        ConnectReply: {
            /**
             * @description Message id of the pending kind=connect row. Required unless
             *     dismissed is true (then the latest pending card in this
             *     transcript is used).
             */
            id?: string;
            /**
             * @description Decline the pending card. Updates that same Message to
             *     connectStatus=dismissed. Does not create a user Message and
             *     does not wake the agent. `{ dismissed: true }` is enough;
             *     `{ id }` after the browser finishes sets connected and wakes
             *     the agent so tools auto-run.
             * @default false
             */
            dismissed: boolean;
        };
        MessageCreate: {
            /**
             * @description User text. Required unless widgetReply, connectReply, or a
             *     non-empty attachmentIds list (image-only / file-only send).
             *     Empty is allowed for those posts. A
             *     normal send while a question is pending is 409 unless
             *     dismissOnMoveOn. A send while a connect card is pending is
             *     409 until connect or dismiss.
             */
            content?: string;
            images?: components["schemas"]["ImageIn"][];
            /**
             * @description Ids from POST /v1/agents/{id}/attachments on this same
             *     conversation. Unknown or foreign ids 422 (do not 404 the
             *     send). Empty content is ok if this list is non-empty.
             *     Runtime includes them in that turn. Assistant rows never
             *     persist attachments this slice.
             */
            attachmentIds?: string[];
            /**
             * @description Agent ids from typeahead chips. Unresolved `@text` is omitted
             *     and is not a mention. Unknown chip ids 422. Runtime also
             *     parses exact `@DisplayName`. Peer deliveries from a 1:1 land
             *     in the seeded channel as a handoff thread when that channel
             *     exists (body `channelId` ignored). After the seed is gone,
             *     log on body `channelId` if it is an existing kind=channel row,
             *     else no log. Unknown/stale ids skip the log (do not 422),
             *     never in another agent's 1:1.
             */
            mentions?: string[];
            /** @description Channel thread id when posting a reply in a thread. */
            replyTo?: string | null;
            /**
             * @description Optional. Used only as the A2A log fallback after seed
             *     `snorlax-bot-group` is gone. Ignored while the seed exists.
             *     After the seed is gone, 1:1 @involves log here if the id is
             *     an existing kind=channel row. Unknown, stale, or agent ids:
             *     skip the log (do not 422, do not recreate seed).
             */
            channelId?: string | null;
            /**
             * @description Answer the pending question card. `{ id, values }` resolves
             *     that same Message. `{ id, dismissed: true }` declines it and
             *     does not wake the agent. Not a user Message. Not a user-right
             *     bubble.
             */
            widgetReply?: components["schemas"]["WidgetReply"];
            /**
             * @description Answer the pending connect card. `{ id }` marks that same
             *     Message connected and wakes the agent. `{ dismissed: true }`
             *     declines it and does not wake the agent. Not a user Message.
             *     Not a user-right bubble.
             */
            connectReply?: components["schemas"]["ConnectReply"];
        };
        MessageDelta: {
            id: string;
            /** @constant */
            role: "assistant";
            /**
             * @description Text chunk of the assistant Message.content string. Concatenate
             *     in order to rebuild content. Not HTML, not a block, not a
             *     second Message.
             */
            delta: string;
            senderId?: string;
            senderName?: string;
            senderAvatar?: string | null;
        };
        ToolTrace: {
            id: string;
            name: string;
            /** @description Muted client line such as "Searching…" or "Wrote app.py". */
            summary: string;
            ok?: boolean | null;
            senderId?: string;
            senderName?: string;
        };
        WorkspaceEntry: {
            name: string;
            /** @enum {string} */
            kind: "file" | "dir";
            /** @description Byte size for files. Omitted for directories. */
            size?: number;
        };
        WorkspaceListing: {
            /**
             * @description Sandbox-relative root (`workspaces/agents/{id}` or
             *     `workspaces/channels/{id}`). Never a host Mac path.
             */
            root: string;
            /** @description Requested path relative to root. Default `.`. */
            path: string;
            entries: components["schemas"]["WorkspaceEntry"][];
        };
        WorkspaceFile: {
            path: string;
            content: string;
            /** @description True when the file was larger than the 256k cap. */
            truncated?: boolean;
        };
        ComputerPreview: {
            /**
             * @description False when this agent has no sandbox. Clients show 12px
             *     muted `No computer yet.` and no frame. True means the
             *     desktop is on (including idle) and imageUrl is a Bearer PNG.
             */
            hasSandbox: boolean;
            /**
             * @description Sandbox display width. Always 1280.
             * @constant
             */
            width: 1280;
            /**
             * @description Sandbox display height. Always 800.
             * @constant
             */
            height: 800;
            /**
             * @description Present only when hasSandbox is true. Path to the Bearer PNG
             *     (`/v1/agents/{id}/computer/screenshot`). Same SNORLAX_TOKEN
             *     as other GETs. Omitted when hasSandbox is false.
             */
            imageUrl?: string;
            /**
             * @description Present when hasSandbox is true. `user` while a takeover
             *     session exists; `agent` after the agent drove the sandbox
             *     (`computer_click` / `computer_key`); `idle` otherwise.
             *     Omitted when hasSandbox is false.
             * @enum {string}
             */
            driving?: "user" | "agent" | "idle";
            /**
             * @description Present when hasSandbox is true. true while POST
             *     `/computer/record` is capturing; false otherwise (idle,
             *     session without Record, or after DELETE `/computer/record`).
             *     Omitted when hasSandbox is false.
             */
            recording?: boolean;
        };
        ComputerSession: {
            /** @description Opaque takeover session id. Same id if POST while already open. */
            sessionId: string;
        };
        ComputerRecording: {
            /** @description true after POST /computer/record. */
            recording: boolean;
        };
        PointerEvent: {
            /** @description Sandbox x in 0..1279 (1280x800). */
            x: number;
            /** @description Sandbox y in 0..799 (1280x800). */
            y: number;
            /** @enum {string} */
            type: "move" | "down" | "up" | "click";
        };
        KeyEvent: {
            /** @description Key name (`a`, `Enter`, `Backspace`, …). */
            key: string;
            /** @enum {string} */
            type: "down" | "up" | "type";
            /**
             * @description Optional string to type. When type is `type`, preferred over
             *     `key` if present.
             */
            text?: string;
        };
        Routine: {
            id: string;
            name: string;
            /** @description SKILL.md slug this routine fires. */
            skill: string;
            /**
             * @description cron XOR webhook / slack / github.
             * @enum {string}
             */
            kind: "cron" | "webhook" | "slack" | "github";
            /** @description Cron only. 5-field cron in Asia/Taipei. Present only for kind=cron. Omitted otherwise. */
            schedule?: string;
            /** @description false is paused. Resume is enabled true. */
            enabled: boolean;
            /** @description Cron display (`Weekdays 9:00`). Present only for kind=cron. */
            scheduleLabel?: string;
            /** @description Present only for kind=webhook. Full POST URL with the secret token in the path (`/v1/hooks/{token}`), not query. Copy this from the identity pane. Clients must not paint it as the muted line. */
            webhookUrl?: string;
            /** @description Optional Slack/GitHub display (e.g. `Slack #eng`, `GitHub owner/repo`). Omitted for cron and webhook. */
            label?: string;
        };
        RoutineTrigger: {
            /** @description webhook, slack, or github. webhook always works (zero plugins). slack/github require GET /v1/plugins status=connected else 422. inbound Slack/GitHub delivery is the connected MCP plugin (no extra HTTP route). */
            type: string;
            /** @description Slack channel (e.g. `#eng`). Required when type=slack. Empty is 422. */
            channel?: string;
            /** @description GitHub `owner/name`. Required when type=github. One repo, no wildcards. Empty/wildcard is 422. */
            repo?: string;
            /** @description Ignored on POST. GET Routine.label is `Slack {channel}` / `GitHub {repo}`. */
            label?: string;
        };
        RoutineCreate: {
            name: string;
            skill: string;
            /** @description Cron XOR trigger. 5-field cron or a named hour (weekdays at 9am). Asia/Taipei. */
            schedule?: string;
            trigger?: components["schemas"]["RoutineTrigger"];
        };
        RoutinePatch: {
            /** @description true = enable/resume. false = pause. */
            enabled: boolean;
        };
        SkillInfo: {
            name: string;
            description: string;
            /** @enum {string} */
            source: "workspace" | "skillsDir";
            /** @description Path relative to the workspace or skills dir. */
            path: string;
        };
        Skill: {
            /**
             * @description Directory slug under SNORLAX_DATA_DIR/skills/<id>/SKILL.md
             *     (v0.9 load path).
             */
            id: string;
            /** @description Frontmatter name (the POST body name). */
            name: string;
        };
        SkillCreate: {
            /**
             * @description Display name for the saved SKILL.md (frontmatter name).
             *     With `body` omitted, writes SNORLAX_DATA_DIR/skills/<slug>/SKILL.md
             *     from the stopped capture. Discard is omit this POST.
             */
            name: string;
            /**
             * @description When present and non-empty, write SKILL.md from this source
             *     (blank New skill; no capture required). Same shape as PATCH
             *     body: full SKILL.md source (frontmatter plus recipe) or
             *     recipe-only. Empty is 422. When omitted, teach-a-task from
             *     the pending capture (unchanged).
             */
            body?: string;
        };
        SkillBody: {
            /**
             * @description Directory slug under SNORLAX_DATA_DIR/skills/<id>/SKILL.md
             *     (v0.9 load path). PATCH does not rename the slug.
             */
            id: string;
            /** @description Frontmatter name. */
            name: string;
            /**
             * @description Full SKILL.md **source** including YAML frontmatter and
             *     recipe (not rendered HTML). Empty on PATCH is 422.
             */
            body: string;
        };
        SkillPatch: {
            name: string;
            /** @description Full SKILL.md source (YAML frontmatter plus recipe). Empty is 422. */
            body: string;
        };
        Plugin: {
            id: string;
            name: string;
            /**
             * @description `connected` when the runtime has a live MCP session.
             *     `needsAuth` otherwise (including disabled / not signed in).
             * @enum {string}
             */
            status: "connected" | "needsAuth";
        };
        /**
         * @description `transport` is `stdio` or `url`. stdio requires `command` (args
         *     optional). url requires `url` (http or https). Missing fields 422.
         */
        PluginCreate: {
            name: string;
            /** @enum {string} */
            transport: "stdio" | "url";
            command?: string;
            args?: string[];
            /** @description LAN MCP URL (http or https). */
            url?: string;
        };
        /**
         * @description Curated catalog row. Same transport fields as PluginCreate.
         *     Null command/args/url are omitted. Not a Plugin (no status).
         */
        PluginCatalogEntry: {
            id: string;
            name: string;
            /** @enum {string} */
            transport: "stdio" | "url";
            command?: string;
            args?: string[];
            /** @description LAN MCP URL (http or https). */
            url?: string;
        };
        PluginAuth: {
            /**
             * @description URL for the OS browser. OAuth callback hits the runtime.
             *     Clients never speak MCP.
             */
            authorizationUrl: string;
        };
        ErrorBody: {
            error: string;
        };
    };
    responses: {
        /** @description `{ error }` as a string */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: {
        Id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    processHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                    };
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON array of Agent (not wrapped) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    patchAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentPatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                limit?: number;
                before?: string;
                /** @description Channel thread id (the handoff root). Returns that thread. */
                threadId?: string;
                /** @description Alias of threadId. */
                replyTo?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON array of Message (not wrapped) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    postMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listRoutines: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON array of Routine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Routine"][];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    createRoutine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineCreate"];
            };
        };
        responses: {
            /** @description Created routine */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Routine"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    deleteRoutine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                routineId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted; no body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    patchRoutine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                routineId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutinePatch"];
            };
        };
        responses: {
            /** @description Updated routine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Routine"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    fireWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Secret token minted into webhookUrl. Not the routine id. */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fired; no body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    listSkills: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON array of Skill `{ id, name }` (not wrapped) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"][];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    createSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillCreate"];
            };
        };
        responses: {
            /** @description Written skill `{ id, name }` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                /**
                 * @description Skill id (directory slug under skills/<sid>/SKILL.md, or
                 *     frontmatter name). Unknown is 404.
                 */
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skill with SKILL.md source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillBody"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    deleteSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                /**
                 * @description Skill id (directory slug under skills/<sid>/SKILL.md, or
                 *     frontmatter name). Unknown is 404.
                 */
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted; no body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    patchSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                /**
                 * @description Skill id (directory slug under skills/<sid>/SKILL.md, or
                 *     frontmatter name). Unknown is 404.
                 */
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillPatch"];
            };
        };
        responses: {
            /** @description Updated skill with SKILL.md source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillBody"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listWorkspace: {
        parameters: {
            query?: {
                /** @description Directory relative to the workspace root. */
                path?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceListing"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getWorkspaceFile: {
        parameters: {
            query?: {
                /** @description File path relative to the workspace root. */
                path?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceFile"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getComputer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Computer preview descriptor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputerPreview"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getComputerScreenshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG screenshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    openComputerSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Takeover session is up */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputerSession"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    closeComputerSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session closed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    closeComputerSessionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session closed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    postComputerPointer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PointerEvent"];
            };
        };
        responses: {
            /** @description Pointer applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    postComputerKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyEvent"];
            };
        };
        responses: {
            /** @description Key applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    startComputerRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capture is running */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputerRecording"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    stopComputerRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capture stopped; no file yet */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON array of Plugin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plugin"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createPlugin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PluginCreate"];
            };
        };
        responses: {
            /** @description Created plugin */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plugin"];
                };
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listPluginCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON array of PluginCatalogEntry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginCatalogEntry"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    deletePlugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uninstalled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    startPluginAuth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Browser URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginAuth"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    postAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created attachment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
