/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Extra process ping (not the locked client ping) */
        get: operations["processHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unauthenticated ping */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agents */
        get: operations["listAgents"];
        put?: never;
        /** Create an agent */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get one agent */
        get: operations["getAgent"];
        put?: never;
        post?: never;
        /**
         * Delete an agent
         * @description kind=agent (including seed `snorlax-bot`) returns 204 and is gone
         *     from GET /v1/agents. The seed is not auto-reseeded; an empty agent
         *     roster is fine. Seeded channel `snorlax-bot-group` returns 409
         *     `{ error }`.
         */
        delete: operations["deleteAgent"];
        options?: never;
        head?: never;
        /**
         * Patch profile fields
         * @description kind=agent (including seed `snorlax-bot`) accepts
         *     `{ name, title, description, avatar }`. Id is not editable.
         *     Empty/null avatar shows initials from name. Avatar is a string
         *     (data URI or persisted `/v1/images/{id}`) or null. There is no
         *     separate avatar upload route.
         *     kind=channel (`snorlax-bot-group`) returns 409 `{ error }`.
         */
        patch: operations["patchAgent"];
        trace?: never;
    };
    "/v1/agents/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * List transcript messages
         * @description Oldest-first. `before` is a message id cursor for older pages.
         *     For kind=agent (including seed `snorlax-bot`), the list is only
         *     `senderId=user` and that agent. Peer/involve/DM/hop messages are
         *     never in a 1:1. For kind=channel (`snorlax-bot-group`) the default
         *     list is the **timeline**: handoff roots (and other unreplied-to
         *     roots). Thread replies are omitted. Pass `threadId` (or `replyTo`)
         *     to load that thread (root + flat replies).
         */
        get: operations["listMessages"];
        put?: never;
        /**
         * Send a user message and stream agent replies
         * @description SSE, chat-only (no tools). Images are stored and returned; never
         *     forwarded to vLLM.
         *
         *     For a 1:1 agent, hop 0 is that agent. Mentioned peers and hops
         *     reply in a `snorlax-bot-group` thread under a kind=handoff root,
         *     not in either 1:1. A still answers in the 1:1. Optional `replyTo`
         *     on the body posts into an existing channel thread.
         *
         *     422 only for an unknown mention chip id (and `@everyone` chip
         *     outside the group). Typed `@foo` with no chip is plain text.
         *     Agent-authored unknown `@Name` is ignored. `@everyone` is group-only.
         *
         *     - event `message.delta` data `{ id, role: "assistant", delta, senderId, senderName, senderAvatar }`
         *     - event `message.done` data full Message (not wrapped)
         *     - event `error` data `{ error }` (string)
         *
         *     Multiple `message.done` events may appear on one stream when more
         *     than one agent speaks in this transcript.
         */
        post: operations["postMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch persisted image bytes
         * @description Supports Message.images[].url. Never sent to the model.
         */
        get: operations["getImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            ok: true;
            /** @constant */
            name: "Snorlax-Bot";
            version: string;
        };
        Agent: {
            /**
             * @description Seed 1:1 is `snorlax-bot`. Seeded channel is `snorlax-bot-group`.
             *     Never reuse `snorlax-bot` as the channel transcript.
             */
            id: string;
            /** @description Display name. Seed 1:1 is Snorlax. Seeded channel is Snorlax-Bot. */
            name: string;
            title: string;
            description: string;
            /**
             * @description Data URI, persisted image id or `/v1/images/{id}` URL, or null.
             *     Empty/null shows initials from name.
             */
            avatar: string | null;
            /**
             * @description Clients show a muted "Channel" subtitle from kind=channel.
             *     Do not guess from id. Seed agent is kind=agent.
             * @enum {string}
             */
            kind: "agent" | "channel";
            /** @description Agent ids in a channel. Empty for kind=agent. Always all agents for the seeded group. */
            memberIds: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AgentCreate: {
            /** @default New agent */
            name: string;
            /** @default  */
            title: string;
            /** @default  */
            description: string;
            avatar?: string | null;
        };
        AgentPatch: {
            name?: string;
            title?: string;
            description?: string;
            /**
             * @description Data URI, persisted image id or `/v1/images/{id}` URL, or null.
             *     Empty/null shows initials from name. Id is not a patch field.
             */
            avatar?: string | null;
        };
        ImageOut: {
            id: string;
            mime: string;
            url: string;
        };
        ImageIn: {
            mime: string;
            /** @description Base64 image bytes. Persisted; never sent to the model. */
            data: string;
        };
        Mention: {
            /** @description Agent id, or `everyone` for @everyone. */
            id: string;
            name: string;
        };
        HandoffRef: {
            channelId: string;
            threadId: string;
        };
        Message: {
            id: string;
            /**
             * @description Transcript owner. `snorlax-bot` is the Snorlax 1:1. `snorlax-bot-group`
             *     is the seeded channel. 1:1 lists are only user + that agent.
             */
            agentId: string;
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
            images: components["schemas"]["ImageOut"][];
            /** Format: date-time */
            createdAt: string;
            /** @description `user` or an agent id. Layout uses senderId === user → right; else left. */
            senderId: string;
            senderName: string;
            senderAvatar: string | null;
            /** @description User→current agent is 0. Mentions increment. Max depth 3. */
            hop: number;
            mentions: components["schemas"]["Mention"][];
            /**
             * @description Channel handoff root is `handoff` (LEFT card authored as A).
             *     Default `message`.
             * @enum {string}
             */
            kind?: "message" | "handoff";
            /** @description Channel thread id. Null on timeline roots and on 1:1s. */
            replyTo?: string | null;
            /**
             * @description Set on the originating **user** message when the user caused a
             *     handoff (an @chip in a 1:1). Absent/null if hop/cap dropped
             *     the mention, or if an agent DM created the thread without a
             *     user @chip. Not a fake speaker.
             */
            handoff?: components["schemas"]["HandoffRef"];
            /** @description Handoff root. The ask B should answer. */
            userAsk?: string | null;
            /**
             * @description Handoff root. Last 8 user+A messages of the originating 1:1,
             *     cap 2k characters, oldest dropped.
             */
            brief?: string | null;
            /** @description Count of thread replies under a timeline root. */
            replyCount?: number;
        };
        MessageCreate: {
            content: string;
            images?: components["schemas"]["ImageIn"][];
            /**
             * @description Agent ids from typeahead chips. Unresolved `@text` is omitted
             *     and is not a mention. Unknown chip ids 422. Runtime also
             *     parses exact `@DisplayName`. Peer deliveries from a 1:1 land
             *     in the seeded channel as a handoff thread, not in another
             *     agent's 1:1.
             */
            mentions?: string[];
            /** @description Channel thread id when posting a reply in a thread. */
            replyTo?: string | null;
        };
        MessageDelta: {
            id: string;
            /** @constant */
            role: "assistant";
            delta: string;
            senderId?: string;
            senderName?: string;
            senderAvatar?: string | null;
        };
        ErrorBody: {
            error: string;
        };
    };
    responses: {
        /** @description `{ error }` as a string */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: {
        Id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    processHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                    };
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON array of Agent (not wrapped) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    patchAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentPatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                limit?: number;
                before?: string;
                /** @description Channel thread id (the handoff root). Returns that thread. */
                threadId?: string;
                /** @description Alias of threadId. */
                replyTo?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON array of Message (not wrapped) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    postMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
